<a href="https://colab.research.google.com/github/Shiva-space-8840/Assigement-/blob/main/Num%2Cpyassigement.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  1. Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.


import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [ ]:
#2. Given a NumPy array 'arr', check if its data type is float64.
   #arr = np.array([1.5, 2.6, 3.7])


import numpy as np

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)

float64


In [ ]:
#3.Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.
import numpy as np
arr = np.array([1+2j, 3-4j, 5+6j], dtype=np.complex128)
print(arr.dtype)

complex128


In [ ]:
#4.Convert an existing NumPy array 'arr' of integers to float32 data type.

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
arr_float32 = arr.astype(np.float32)
print(arr_float32)



[1. 2. 3. 4. 5.]


In [ ]:
#5. Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.
import numpy as np
arr = np.array([1.123456789, 2.987654321, 3.456789123])
arr1 = arr.astype(np.float64)
print(arr1)
arr1.dtype
##########  Convert ##################
print('Convert float64 to float32')
arr2=arr.astype(np.float32)
print(arr2)
print(arr2.dtype)

[1.12345679 2.98765432 3.45678912]
Convert float64 to float32
[1.1234568 2.9876542 3.456789 ]
float32


In [ ]:
#6. Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type.

import numpy as np

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype
arr = np.array([[1, 2, 3], [4, 5, 6],[8,9,11]])
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (3, 3)
Size: 9
Data type: int64


In [ ]:
'''Q 7 Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.'''
def array_dimension(arr):
    return arr.ndim
arr_1d = np.array([1, 2, 3])
arr_2d = np.array([[1, 2], [3, 4]])
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr_4d = np.array([[[[1,2],[3,4],[5,6],[7,8]]]])
print("Dimension of arr_1d:", array_dimension(arr_1d))
print("Dimension of arr_2d:", array_dimension(arr_2d))
print("Dimension of arr_3d:", array_dimension(arr_3d))
print("Dimension of arr_4:",  array_dimension(arr_4d))

Dimension of arr_1d: 1
Dimension of arr_2d: 2
Dimension of arr_3d: 3
Dimension of arr_4: 4


In [ ]:
# 8. 8. Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes.
import numpy as np

def item_size_info(arr):
    item_size = arr.itemsize
    total_size = arr.nbytes
    return item_size, total_size
arr = np.array([[1, 2, 3,7], [4, 5, 6,8]])
item_size, total_size = item_size_info(arr)
print("Item size (in bytes):", item_size)
print("Total size (in bytes):", total_size)

Item size (in bytes): 8
Total size (in bytes): 64


In [ ]:
# 9. Create a function array_strides that takes a NumPy array as input and returns the strides of the array.
import numpy as np

def array_strides(arr):
    return arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array strides:", array_strides(arr))


Array strides: (24, 8)


In [ ]:
# 10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.
import numpy as np

def shape_stride_relationship(arr):
    return arr.shape, arr.strides
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
shape, strides = shape_stride_relationship(arr)
print("Array shape:", shape)
print("Array strides:", strides)


Array shape: (3, 3)
Array strides: (24, 8)


In [ ]:
# 11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.
import numpy as np

def create_zeros_array(a):
    return np.zeros(a)
a = 5
zeros_arr = create_zeros_array(a)
print("Zeros array with", a, "elements:", zeros_arr)


Zeros array with 5 elements: [0. 0. 0. 0. 0.]


In [ ]:
# 12. Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.
import numpy as np

def create_ones_matrix(rows, cols):
    return np.ones((rows, cols))
rows = 4
cols = 5
ones_matrix = create_ones_matrix(rows, cols)
print("Ones matrix of size", rows, "x", cols, ":", ones_matrix)


Ones matrix of size 4 x 5 : [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
# 13. Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified step.
import numpy as np

def generate_range_array(start, stop, step):
    return np.arange(start, stop, step)

# Example usage:
start = 1
stop = 20
step = 3
range_array = generate_range_array(start, stop, step)
print("Generated array:", range_array)


Generated array: [ 1  4  7 10 13 16 19]


In [ ]:
import numpy as np

def generate_linear_space(start, stop, num):
    return np.linspace(start, stop, num)

# Example usage:
start = 1
stop = 20
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print("Generated linear space array:", linear_space_array)


Generated linear space array: [ 1.    5.75 10.5  15.25 20.  ]


In [ ]:
# 15. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.
import numpy as np

def create_identity_matrix(n):
    return np.eye(n)
n = 6
identity_matrix = create_identity_matrix(n)
print("Identity matrix of size", n, "x", n, ":\n", identity_matrix)


Identity matrix of size 6 x 6 :
 [[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [ ]:
#16. Write a function that takes a Python list and converts it into a NumPy array.
import numpy as np

def list_to_numpy_array(lst):
    return np.array(lst)
my_list = [10, 20, 35, 45, 50]
array = list_to_numpy_array(my_list)
print("NumPy array:",array)


NumPy array: [10 20 35 45 50]


In [ ]:
# 17. Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.
import numpy as np
original_array = np.array([[1, 2, 3], [4, 5, 6]])
view_array = original_array.view()
view_array[0, 0] = 100
print("Original array:\n", original_array)
print("View array:\n", view_array)


Original array:
 [[100   2   3]
 [  4   5   6]]
View array:
 [[100   2   3]
 [  4   5   6]]


In [ ]:
# 18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.
import numpy as np
def concatenate_arrays(arr1, arr2, axis=0):
  return np.concatenate((arr1, arr2), axis=0)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
concatenated_array = np.concatenate((arr1, arr2), axis=0)
print(concatenated_array)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
# 19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.concatenate`.
import numpy as np
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[7, 8],
                 [9, 10]])
concatenated_array = np.concatenate((arr1, arr2), axis=1)

print("Array 1:")
print(arr1)
print("\nArray 2:")
print(arr2)
print("\nConcatenated array horizontally:")
print(concatenated_array)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8]
 [ 9 10]]

Concatenated array horizontally:
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [ ]:
# 20. . Write a function that vertically stacks multiple NumPy arrays given as a list.

import numpy as np

def stack_arrays_vertically(arrays):
    return np.vstack(arrays)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr3 = np.array([[9, 10], [11, 12]])

stacked_array = stack_arrays_vertically([arr1, arr2, arr3])
print(stacked_array)


[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
# 21.21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.
import numpy as np

def create_integer_array(start, stop, step):
    return np.arange(start, stop+1, step, dtype=int)
start = 0
stop = 50
step = 5
result = create_integer_array(start, stop, step)
print(result)


[ 0  5 10 15 20 25 30 35 40 45 50]


In [ ]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).
import numpy as np

def generate_equally_spaced_values():
    return np.linspace(0, 1, 10)
result = generate_equally_spaced_values()
print(result)



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
import numpy as np

def generate_logarithmically_spaced_values():
    return np.logspace(start=np.log10(1), stop=np.log10(1000), num=5)
result = generate_logarithmically_spaced_values()
print(result)


[   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [ ]:
#24.. Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100 .
import numpy as np
import pandas as pd

# Create a NumPy array of random integers between 1 and 100
np.random.seed(42)  # For reproducibility
data = np.random.randint(1, 101, size=(5, 3))

# Create a Pandas DataFrame using the NumPy array
df = pd.DataFrame(data, columns=['Column1', 'Column2', 'Column3'])

print(df)


   Column1  Column2  Column3
0       52       93       15
1       72       61       21
2       83       87       75
3       75       88      100
4       24        3       22


In [ ]:
# 25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

import pandas as pd

def replace_negative_with_zeros(df, column_name):
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df
data = {'A': [1, 2, -3, 4, -5],
        'B': [5, -6, 7, -8, 9]}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df = replace_negative_with_zeros(df, 'A')
df=replace_negative_with_zeros(df,'B')

print("\nDataFrame with negative values replaced by zeros:")
print(df)


Original DataFrame:
   A  B
0  1  5
1  2 -6
2 -3  7
3  4 -8
4 -5  9

DataFrame with negative values replaced by zeros:
   A  B
0  1  5
1  2  0
2  0  7
3  4  0
4  0  9


In [ ]:
#26. Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

import numpy as np

arr = np.array([10, 20, 30, 40, 50])
third_element = arr[2]

print("Third element:", third_element)



Third element: 30


In [ ]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
element_12 = arr_2d[1, 2]

print("Element at index (1, 2):", element_12)


Element at index (1, 2): 6


In [ ]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7,200])

result = arr[arr > 5]

print("Elements greater than 5:", result)



Elements greater than 5: [  8  10   7 200]


In [ ]:
#29. Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

result = arr[2:6]

print("Elements from index 2 to 5 (inclusive):", result)


Elements from index 2 to 5 (inclusive): [3 4 5 6]


In [ ]:
#30. Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
import numpy as np

arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

sub_array = arr_2d[0:2, 1:]

print("Sub-array [[2, 3], [5, 6]]:")
print(sub_array)


Sub-array [[2, 3], [5, 6]]:
[[2 3]
 [5 6]]


In [ ]:
#31.Write a NumPy function to extract elements in specific order from a given 2D array based on indices provided in another array.
import numpy as np

def extract_elements_by_indices(arr_2D, indices):
    return arr_2D.ravel()[indices]

arr_2D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

indices = np.array([1, 4, 2, 5, 7])

result = extract_elements_by_indices(arr_2D, indices)
print("Extracted elements based on indices:", result)


Extracted elements based on indices: [2 5 3 6 8]


In [ ]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.
import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    return arr[arr > threshold]

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
threshold = 5

result = filter_elements_greater_than_threshold(arr, threshold)
print("Filtered elements greater than", threshold, ":", result)


Filtered elements greater than 5 : [6 7 8 9]


In [ ]:
#33. Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.
import numpy as np

def extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3):
    return arr_3d[indices_dim1, indices_dim2, indices_dim3]
arr_3d = np.array([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[10, 11, 12],
                    [13, 14, 15],
                    [16, 17, 18]],
                   [[19, 20, 21],
                    [22, 23, 24],
                    [25, 26, 27]]])

indices_dim1 = np.array([0, 1, 2])
indices_dim2 = np.array([1, 2, 0])
indices_dim3 = np.array([2, 0, 1])

result = extract_elements_from_3d_array(arr_3d, indices_dim1, indices_dim2, indices_dim3)
print("Extracted elements:")
print(result)


Extracted elements:
[ 6 16 20]


In [ ]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
import numpy as np

def elements_satisfying_conditions(arr, condition1, condition2):
    return arr[np.logical_and(condition1, condition2)]
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,12,32,64])
condition1 = arr > 3
condition2 = arr % 2 == 0

result = elements_satisfying_conditions(arr, condition1, condition2)
print("Elements satisfying both conditions:")
print(result)



Elements satisfying both conditions:
[ 4  6  8 12 32 64]


In [ ]:
#35. Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.
import numpy as np

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 0, 2])

result = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)
print("Extracted elements:")
print(result)


Extracted elements:
[2 4 9]


In [ ]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.
import numpy as np

# Create the array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

result = arr + 10

print(result)


[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [ ]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.
import numpy as np

# Create arr1 of shape (1, 3)
arr1 = np.array([[2, 3, 4]])

# Create arr2 of shape (3, 4)
arr2 = np.array([[1, 2, 3,4],
                 [5, 6, 7,8],
                 [9, 10, 11,12]])

result = arr1 * arr2

print(result)


ValueError: operands could not be broadcast together with shapes (1,3) (3,4) 

In [1]:
#38. Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.
import numpy as np

# Create arr1 of shape (1, 4)
arr1 = np.array([[1],
                 [2],
                 [3],
                 [4]])

# Create arr2 of shape (4, 3)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])

result = arr1 + arr2

print(result)

[[ 6  7  8]
 [10 11 12]
 [14 15 16]
 [18 19 20]]


In [2]:
#39. Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.
import numpy as np

# Define the arrays
arr1 = np.array([[1], [2], [3]])  # Shape (3, 1)
arr2 = np.array([[4, 5, 6]])      # Shape (1, 3)

# Perform broadcasting and addition
result = arr1 + arr2

# Output the result
print(result)


[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [4]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility
import numpy as np
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8], [9, 10]])
arr2_reshaped = arr2[:, :, np.newaxis]
result = arr1 * arr2_reshaped
print(result)


[[[ 7 14 21]
  [32 40 48]]

 [[ 9 18 27]
  [40 50 60]]]


In [5]:
#41. Calculate column wise mean for the given array:arr = np.array([[1, 2, 3], [4, 5, 6]]).
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_mean = np.mean(arr, axis=0)
print(column_mean)


[2.5 3.5 4.5]


In [6]:
#42. Find maximum value in each row of the given array:arr = np.array([[1, 2, 3], [4, 5, 6]]).
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
row_max = np.max(arr, axis=1)

print(row_max)


[3 6]


In [8]:
#43.. For the given array, find indices of maximum value in each column.arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
column_max_indices = np.argmax(arr, axis=0)
print(column_max_indices)


[1 1 1]


In [10]:
#44. For the given array, apply custom function to calculate moving sum along rows.arr = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np


arr = np.array([[1, 2, 3], [4, 5, 6]])
def moving_sum(arr, window_size=2):
    result = np.array([np.convolve(row, np.ones(window_size), mode='valid') for row in arr])
    return result
result = moving_sum(arr, window_size=2)
print(result)


[[ 3.  5.]
 [ 9. 11.]]


In [11]:
#45. In the given array, check if all elements in each column are even.arr = np.array([[2, 4, 6], [3, 5, 7]]).
import numpy as np
arr = np.array([[2, 4, 6], [3, 5, 7]])
even_check = np.all(arr % 2 == 0, axis=0)

print(even_check)


[False False False]


In [12]:
#46. Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.original_array = np.array([1, 2, 3, 4, 5, 6])
import numpy as np

original_array = np.array([1, 2, 3, 4, 5, 6])

reshaped_matrix = original_array.reshape(2, 3)

print(reshaped_matrix)


[[1 2 3]
 [4 5 6]]


In [14]:
#47.Create a function that takes a matrix as input and returns the flattened array.input_matrix = np.array([[1, 2, 3], [4, 5, 6]])
import numpy as np

def flatten_matrix(matrix):
    return matrix.flatten()

input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

flattened_array = flatten_matrix(input_matrix)
print(flattened_array)


[1 2 3 4 5 6]


In [16]:
#48.Write a function that concatenates two given arrays along a specified axis.
#array1 = np.array([[1, 2], [3, 4]]) ,array2 = np.array([[5, 6], [7, 8]])
import numpy as np
def concatenate_arrays(array1, array2, axis=0):
    return np.concatenate((array1, array2), axis=axis)
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

result_axis0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenation along axis 0 (rows):")
print(result_axis0)
result_axis1 = concatenate_arrays(array1, array2, axis=1)
print("Concatenation along axis 1 (columns):")
print(result_axis1)


Concatenation along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenation along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]


In [18]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
import numpy as np
def split_array(array, num_splits, axis=0):
    return np.array_split(array, num_splits, axis=axis)
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
split_axis0 = split_array(original_array, 3, axis=0)
print("Split along axis 0 (rows):")
for sub_array in split_axis0:
    print(sub_array)
split_axis0


Split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [20]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
#original_array = np.array([1, 2, 3, 4, 5])
#indices_to_insert = [2, 4]
#values_to_insert = [10, 11]
#indices_to_delete = [1, 3]

import numpy as np

def insert_and_delete(array, indices_to_insert, values_to_insert, indices_to_delete):
    modified_array = np.insert(array, indices_to_insert, values_to_insert)
    print(f"Array after insertion: {modified_array}")
    modified_array = np.delete(modified_array, indices_to_delete)
    print(f"Array after deletion: {modified_array}")
    return modified_array
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]
result = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)


Array after insertion: [ 1  2 10  3  4 11  5]
Array after deletion: [ 1 10  4 11  5]


In [22]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.
import numpy as np
arr1 = np.random.randint(1, 20, size=5)
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 + arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise addition:", result)


arr1: [ 8  3 10  7 14]
arr2: [1 2 3 4 5]
Result of element-wise addition: [ 9  5 13 11 19]


In [23]:
#52.Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
import numpy as np
arr1 = np.arange(10, 0, -1)
arr2 = np.arange(1, 11)
result = arr1 - arr2
print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise subtraction:", result)


arr1: [10  9  8  7  6  5  4  3  2  1]
arr2: [ 1  2  3  4  5  6  7  8  9 10]
Result of element-wise subtraction: [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [25]:
#53.Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.Perform element-wise multiplication between `arr1` and `arr2`.
import numpy as np
arr1 = np.random.randint(1, 10, size=5)
arr2 = np.array([1, 2, 3, 4, 5])
result = arr1 * arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise multiplication:", result)


arr1: [4 4 3 8 6]
arr2: [1 2 3 4 5]
Result of element-wise multiplication: [ 4  8  9 32 30]


In [31]:
#54.. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
import numpy as np
arr1 = np.arange(2, 11, 2)
arr2 = np.array([1, 2, 3, 4, 5])

result = arr1 / arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise division:",result)


arr1: [ 2  4  6  8 10]
arr2: [1 2 3 4 5]
Result of element-wise division: [2. 2. 2. 2. 2.]


In [32]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
import numpy as np

arr1 = np.arange(1, 6)
arr2 = arr1[::-1]
result = arr1 ** arr2

print("arr1:", arr1)
print("arr2:", arr2)
print("Result of element-wise exponentiation:", result)


arr1: [1 2 3 4 5]
arr2: [5 4 3 2 1]
Result of element-wise exponentiation: [ 1 16 27 16  5]


In [33]:
#56.Write a function that counts the occurrences of a specific substring within a NumPy array of strings.arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
import numpy as np
def count_substring_occurrences(arr, substring):
    occurrences = np.char.count(arr, substring)
    return occurrences.sum()
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
substring = 'hello'
result = count_substring_occurrences(arr, substring)
print(f"Total occurrences of '{substring}':", result)


Total occurrences of 'hello': 3


In [34]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.arr = np.array(['Hello', 'World', 'OpenAI', 'GPT']) arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
import numpy as np
def extract_uppercase(arr):
    uppercase_chars = []
    for string in arr:
        uppercase_chars.extend([char for char in string if char.isupper()])
    return uppercase_chars
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
result = extract_uppercase(arr)
print("Uppercase characters:", result)


Uppercase characters: ['H', 'W', 'O', 'A', 'I', 'G', 'P', 'T']


In [35]:
#58.Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np
def replace_substring(arr, old_substring, new_substring):
    replaced_arr = np.char.replace(arr, old_substring, new_substring)

    return replaced_arr
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
old_substring = 'apple'
new_substring = 'orange'
result = replace_substring(arr, old_substring, new_substring)
print("Array after replacement:", result)


Array after replacement: ['orange' 'banana' 'grape' 'pineorange']


In [37]:
#59.Write a function that concatenates strings in a NumPy array element-wise.arr1 = np.array(['Hello', 'World']) ,arr2 = np.array(['Open', 'AI'])
import numpy as np
def concatenate_strings(arr1, arr2):
    concatenated_arr = np.char.add(arr1, arr2)

    return concatenated_arr
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])
result = concatenate_strings(arr1, arr2)
print("Concatenated array:", result)



Concatenated array: ['HelloOpen' 'WorldAI']


In [38]:
#60. Write a function that finds the length of the longest string in a NumPy array.arr = np.array(['apple', 'banana', 'grape', 'pineapple']),arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
import numpy as np
def longest_string_length(arr):
    lengths = np.char.str_len(arr)
    return np.max(lengths)
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
result = longest_string_length(arr)
print("Length of the longest string:", result)


Length of the longest string: 9


In [39]:
#61.. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.
import numpy as np
dataset = np.random.randint(1, 1001, size=100)
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_deviation = np.std(dataset)
print("Dataset:", dataset)
print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)


Dataset: [375  18 366 317 424 535 892 167 715 835 584  24 500 154 240 306 718 302
 435 460 373 113 656  14 192 417  80 928 578 922  28 149 124 796 110 572
 178 183 339 117 264 888  47 263 470 252  59  12 321 827 890 224 773 129
 407 312 268 854 129 728 462 668 182 726 812 564 752 833 841 459 696 754
 680  47  60 918 508 187 176   2 636 397 805 800 665 757 203 465 939 558
 277 583 617 140 202 988 798 789 361 158]
Mean: 448.18
Median: 420.5
Variance: 83097.3276
Standard Deviation: 288.26607084428093


In [40]:
#62.. Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.
import numpy as np
dataset = np.random.randint(1, 101, size=50)

percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)
print("Dataset:", dataset)
print("25th Percentile:", percentile_25)
print("75th Percentile:", percentile_75)




Dataset: [ 37  86  12  60  27  67  93  54  81  71  87  35  55   8  48  46  60  96
  35  92  26  23  89  52  18  46 100  12  94  41   8   9  72  22  89  52
  13  12  43  54  76  54  47  45  61   5   3  68  52  39]
25th Percentile: 26.25
75th Percentile: 70.25


In [41]:
#63.Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([5, 4, 3, 2, 1])
correlation_matrix = np.corrcoef(array1, array2)
print("Correlation Coefficient Matrix:")
print(correlation_matrix)
correlation_coefficient = correlation_matrix[0, 1]
print("\nCorrelation Coefficient between array1 and array2:", correlation_coefficient)


Correlation Coefficient Matrix:
[[ 1. -1.]
 [-1.  1.]]

Correlation Coefficient between array1 and array2: -0.9999999999999999


In [67]:
#64. Create two matrices and perform matrix multiplication using NumPy's `dot` function.import numpy as np
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print("Matrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

print("\nMatrix Multiplication Result:")
print(result)


Matrix 1:
[[1 2]
 [3 4]]

Matrix 2:
[[5 6]
 [7 8]]

Matrix Multiplication Result:
[[19 22]
 [43 50]]


In [43]:
#65.Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.
import numpy as np
dataset = np.random.randint(10, 1001, size=50)
percentile_10 = np.percentile(dataset, 10)
percentile_50 = np.percentile(dataset, 50)
percentile_90 = np.percentile(dataset, 90)
first_quartile = np.quantile(dataset, 0.25)
third_quartile = np.quantile(dataset, 0.75)
print("Dataset:", dataset)
print("10th Percentile:", percentile_10)
print("50th Percentile (Median):", percentile_50)
print("90th Percentile:", percentile_90)
print("First Quartile (25th Percentile):", first_quartile)
print("Third Quartile (75th Percentile):", third_quartile)


Dataset: [941 415 723 760 739 621 269 796 223 119 577 576 480 895 738 212 391 344
 451 305 778  29 606 653 730 510 658 733 449 601 459 835 317 846 630 230
 481 123 335 200 570 344 693 673 630 745 394 291 320 223]
10th Percentile: 221.9
50th Percentile (Median): 540.0
90th Percentile: 779.8000000000001
First Quartile (25th Percentile): 323.75
Third Quartile (75th Percentile): 715.5


In [44]:
#66.Create a NumPy array of integers and find the index of a specific element.
import numpy as np
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
element_to_find = 40
indices = np.where(arr == element_to_find)
print(f"Array: {arr}")
print(f"Index of element {element_to_find}: {indices[0][0]}")


Array: [ 10  20  30  40  50  60  70  80  90 100]
Index of element 40: 3


In [46]:
#67.Generate a random NumPy array and sort it in ascending order.
import numpy as np
random_array = np.random.randint(1, 101, size=10)
sorted_array = np.sort(random_array)
print("Original Random Array:", random_array)
print("Sorted Array (Ascending):", sorted_array)


Original Random Array: [90 28 91 17 78  5  2 46 42 65]
Sorted Array (Ascending): [ 2  5 17 28 42 46 65 78 90 91]


In [47]:
#68. Filter elements >20  in the given NumPy array.arr = np.array([12, 25, 6, 42, 8, 30])
import numpy as np
arr = np.array([12, 25, 6, 42, 8, 30])

filtered_elements = arr[arr > 20]
print("Original Array:", arr)
print("Filtered Elements (greater than 20):", filtered_elements)


Original Array: [12 25  6 42  8 30]
Filtered Elements (greater than 20): [25 42 30]


In [48]:
#69. Filter elements which are divisible by 3 from a given NumPy array.arr = np.array([1, 5, 8, 12, 15])
import numpy as np
arr = np.array([1, 5, 8, 12, 15])
filtered_elements = arr[arr % 3 == 0]

print("Original Array:", arr)
print("Filtered Elements (divisible by 3):", filtered_elements)


Original Array: [ 1  5  8 12 15]
Filtered Elements (divisible by 3): [12 15]


In [49]:
#70.. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.arr = np.array([10, 20, 30, 40, 50])
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
filtered_elements = arr[(arr >= 20) & (arr <= 40)]
print("Original Array:", arr)
print("Filtered Elements (≥ 20 and ≤ 40):", filtered_elements)


Original Array: [10 20 30 40 50]
Filtered Elements (≥ 20 and ≤ 40): [20 30 40]


In [50]:
#71. For the given NumPy array, check its byte order using the `dtype` attribute byteorder.arr = np.array([1, 2, 3])
import numpy as np
arr = np.array([1, 2, 3])
byte_order = arr.dtype.byteorder
print(f"Byte order of the array: {byte_order}")


Byte order of the array: =


In [51]:
# 72.For the given NumPy array, perform byte swapping in place using `byteswap()`.arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.byteswap()
print("Original Array:", arr)
print("Array after Byte Swapping:", arr_swapped)


Original Array: [1 2 3]
Array after Byte Swapping: [16777216 33554432 50331648]


In [52]:
#73. For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)
import numpy as np
arr = np.array([1, 2, 3], dtype=np.int32)
arr_swapped = arr.newbyteorder()
print("Original Array:", arr)
print("Array after Byte Order Swap:", arr_swapped)


Original Array: [1 2 3]
Array after Byte Order Swap: [16777216 33554432 50331648]


In [53]:
#74.. For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.arr = np.array([1, 2, 3], dtype=np.int32)

import numpy as np
import sys
arr = np.array([1, 2, 3], dtype=np.int32)
system_endianness = sys.byteorder
if system_endianness == 'little':
    arr_swapped = arr.newbyteorder('>')
else:
    arr_swapped = arr.newbyteorder('<')
print("Original Array:", arr)
print("Array after Conditional Byte Order Swap:", arr_swapped)


Original Array: [1 2 3]
Array after Conditional Byte Order Swap: [16777216 33554432 50331648]


In [54]:
#76.. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
import numpy as np
arr1 = np.arange(1, 11)
copy_arr = arr1.copy()
copy_arr[0] = 100
print("Original Array (arr1):", arr1)
print("Modified Copy Array (copy_arr):", copy_arr)


Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified Copy Array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [55]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.
import numpy as np
matrix = np.random.randint(1, 10, size=(3, 3))
view_slice = matrix[:2, :2]
view_slice[0, 0] = 100

print("Original Matrix (matrix):")
print(matrix)
print("\nModified Slice (view_slice):")
print(view_slice)


Original Matrix (matrix):
[[100   7   1]
 [  2   4   1]
 [  8   6   2]]

Modified Slice (view_slice):
[[100   7]
 [  2   4]]


In [56]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
import numpy as np
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[:2, :2]
view_b += 5
print("Original Array (array_a):")
print(array_a)
print("\nModified Slice (view_b):")
print(view_b)


Original Array (array_a):
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

Modified Slice (view_b):
[[ 6  7]
 [ 9 10]]


In [57]:
#79.Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
import numpy as np
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)

reshaped_view[0, 0] = 100
print("Original Array (orig_array):")
print(orig_array)
print("\nReshaped View (reshaped_view):")
print(reshaped_view)


Original Array (orig_array):
[[100   2   3   4]
 [  5   6   7   8]]

Reshaped View (reshaped_view):
[[100   2]
 [  3   4]
 [  5   6]
 [  7   8]]


In [59]:
#80.Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.
import numpy as np
data = np.random.randint(1, 11, size=(3, 4))
data_copy = data[data > 5].copy()
data_copy[0] = 100

print("Original Data (data):")
print(data)
print("\nModified Copy (data_copy):")
print(data_copy)


Original Data (data):
[[ 2  5  6  5]
 [ 7  6 10  4]
 [ 7  6  2 10]]

Modified Copy (data_copy):
[100   7   6  10   7   6  10]


In [62]:
#81. Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.
import numpy as np

A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

addition_result = A + B
subtraction_result = A - B


print("Matrix A:")
print(A)
print("\nMatrix B:")
print(B)
print("\nAddition of A and B:")
print(addition_result)
print("\nSubtraction of A and B:")
print(subtraction_result)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Addition of A and B:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction of A and B:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [63]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
import numpy as np

C = np.array([[1, 2], [3, 4], [5, 6]])
D = np.array([[7, 8, 9, 10], [11, 12, 13, 14]])

matrix_multiplication_result = np.dot(C, D)

print(C)
print("\nMatrix D (2x4):")
print(D)
print("\nResult of Matrix Multiplication (C @ D):")
print(matrix_multiplication_result)





Matrix C (3x2):
[[1 2]
 [3 4]
 [5 6]]

Matrix D (2x4):
[[ 7  8  9 10]
 [11 12 13 14]]

Result of Matrix Multiplication (C @ D):
[[ 29  32  35  38]
 [ 65  72  79  86]
 [101 112 123 134]]


In [64]:
#83. Create a matrix `E` and find its transpose.
import numpy as np
E = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
E_transpose = E.T
print("Original Matrix E:")
print(E)
print("\nTranspose of Matrix E:")
print(E_transpose)


Original Matrix E:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transpose of Matrix E:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [65]:
#84. Generate a square matrix `F` and compute its determinant.
import numpy as np

F = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

det_F = np.linalg.det(F)

print("Original Matrix F:")
print(F)
print("\nDeterminant of Matrix F:")
print(det_F)


Original Matrix F:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Determinant of Matrix F:
0.0


In [66]:
#85. Create a square matrix `G` and find its inverse.
import numpy as np
G = np.array([[4, 7], [2, 6]])
try:
    G_inverse = np.linalg.inv(G)

    print("Original Matrix G:")
    print(G)
    print("\nInverse of Matrix G:")
    print(G_inverse)
except np.linalg.LinAlgError:
    print("Matrix G is singular and does not have an inverse.")


Original Matrix G:
[[4 7]
 [2 6]]

Inverse of Matrix G:
[[ 0.6 -0.7]
 [-0.2  0.4]]
